apiVersion: v1
entries:
  hermes-web-ui:
  - apiVersion: v2
    appVersion: v0.6.14
    created: "2026-06-12T10:27:08.144834419Z"
    description: Helm chart for Hermes Web UI (bundles the full Hermes Agent) on Kubernetes
    digest: e9e0ea29619ada3cc07ee7e5363b1649f22821ee24fb44f261f70bc9cede26b4
    home: https://hermes-agent.nousresearch.com/
    keywords:
    - hermes
    - ai-agent
    - llm
    - anthropic
    - openai
    maintainers:
    - name: liuxiaohui
    name: hermes-web-ui
    sources:
    - https://github.com/NousResearch/hermes-agent
    - https://github.com/EKKOLearnAI/hermes-web-ui
    type: application
    urls:
    - https://0xBitWild.github.io/Charts/charts/hermes-web-ui-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.6.13
    created: "2026-06-12T10:27:08.144155742Z"
    description: Helm chart for Hermes Web UI (bundles the full Hermes Agent) on Kubernetes
    digest: f405ddf739246fe85cbaf0207ff61a004547622d8d247c2ee8e5b03398c193c0
    home: https://hermes-agent.nousresearch.com/
    keywords:
    - hermes
    - ai-agent
    - llm
    - anthropic
    - openai
    maintainers:
    - name: liuxiaohui
    name: hermes-web-ui
    sources:
    - https://github.com/NousResearch/hermes-agent
    - https://github.com/EKKOLearnAI/hermes-web-ui
    type: application
    urls:
    - https://0xBitWild.github.io/Charts/charts/hermes-web-ui-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-12T10:27:08.143372438Z"
